service: fastapi-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  stage: dev
  timeout: 30

package:
  patterns:
    - '!node_modules/**'
    - '!venv/**'
    - '!__pycache__/**'
    - '!.git/**'

functions:
  api:
    handler: app.lambda_handler.handler
    individually: true 
    events:
      - httpApi:
          path: /{proxy+}
          method: '*'
    pythonRequirements:
      dockerizePip: false
      zip: true
      slim: true
      requirementsFile: requirements.txt

plugins:
  - serverless-python-requirements

custom: {}
